# Generated by Django 5.0.4 on 2024-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('response', models.BooleanField(default=True)),
                ('score2', models.IntegerField()),
                ('score3', models.IntegerField()),
                ('response2', models.BooleanField(default=True)),
            ],
        ),
    ]
