# Generated by Django 5.0.4 on 2024-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0002_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='play',
            name='response2',
            field=models.BooleanField(default=False),
        ),
    ]
