# Generated by Django 3.2.12 on 2024-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
