# Generated by Django 3.2.12 on 2024-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_comment_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.ManyToManyField(to='clients.Comment'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='comments',
            field=models.ManyToManyField(to='clients.Comment'),
        ),
    ]
