# Generated by Django 3.2.12 on 2024-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20240427_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.ManyToManyField(blank=True, to='clients.Comment'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='comments',
            field=models.ManyToManyField(blank=True, to='clients.Comment'),
        ),
    ]
